-- Abo-Angebote (Memberships) als eigene Tabelle, damit Admins Preise und
-- Angebote in der App pflegen können statt im Code. Freitext-Felder, weil
-- die Angaben reine Anzeige sind (keine Buchungslogik dahinter).
-- classes: kommagetrennte Liste, wird in der App als Chips angezeigt.

CREATE TABLE memberships (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  duration TEXT NOT NULL,
  check_ins TEXT NOT NULL,
  classes TEXT NOT NULL DEFAULT '',
  price TEXT NOT NULL,
  price_note TEXT NOT NULL DEFAULT 'einmalig',
  is_active BOOLEAN NOT NULL DEFAULT true,
  sort_order INTEGER NOT NULL DEFAULT 0
);

ALTER TABLE memberships ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can view memberships"
ON memberships FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Admins can insert memberships"
ON memberships FOR INSERT
WITH CHECK (is_admin());

CREATE POLICY "Admins can update memberships"
ON memberships FOR UPDATE
USING (is_admin());

CREATE POLICY "Admins can delete memberships"
ON memberships FOR DELETE
USING (is_admin());

-- Startbestand: aktuelles Angebot (Stand Juli 2026, übernommen aus box base).
INSERT INTO memberships (name, duration, check_ins, classes, price, price_note, sort_order) VALUES
  ('10er Abo.', '60 Monate gültig', '10 Check-ins', 'Box-WOD, Cardio, Competition-Class, Early-Bird, Hyrox, MUM-Class, Mittags WOD, Strength Tuesday', 'CHF 220.00', 'einmalig', 1),
  ('10er Abo. Kids', '60 Monate gültig', '10 Check-ins', 'KIDS-Class', 'CHF 120.00', 'einmalig', 2),
  ('10er Abo. MUM', '60 Monate gültig', '10 Check-ins', 'MUM-Class', 'CHF 190.00', 'einmalig', 3),
  ('Drop-IN', '60 Monate gültig', '1 Check-in', 'Box-WOD, Cardio, Early-Bird, Hyrox, KIDS-Class, MUM-Class, Mittags WOD, Open Gym, Strength Tuesday', 'CHF 25.00', 'einmalig', 4),
  ('Foundation', '1 Monat gültig', 'Unbegrenzte Check-ins', 'Box-WOD, Cardio, Early-Bird, Hyrox, MUM-Class, Mittags WOD, Strength Tuesday', 'CHF 210.00', 'einmalig', 5),
  ('Halbjahresabo Bronze', '6 Monate gültig', '1 Check-in pro Woche', 'Box-WOD, Cardio, Competition-Class, Early-Bird, Hyrox, MUM-Class, Mittags WOD, Strength Tuesday', 'CHF 450.00', 'einmalig', 6),
  ('Halbjahresabo Gold', '6 Monate gültig', 'Unbegrenzte Check-ins', 'Box-WOD, Cardio, Competition-Class, Early-Bird, Hyrox, MUM-Class, Mittags WOD, Strength Tuesday', 'CHF 990.00', 'einmalig', 7),
  ('Halbjahresabo Silber', '6 Monate gültig', '2 Check-ins pro Woche', 'Box-WOD, Cardio, Competition-Class, Early-Bird, Hyrox, MUM-Class, Mittags WOD, Strength Tuesday', 'CHF 840.00', 'einmalig', 8),
  ('Jahresabo Bronze', '12 Monate gültig', '1 Check-in pro Woche', 'Box-WOD, Cardio, Competition-Class, Early-Bird, Hyrox, MUM-Class, Mittags WOD, Strength Tuesday', 'CHF 990.00', 'einmalig', 9),
  ('Jahresabo Gold', '12 Monate gültig', 'Unbegrenzte Check-ins', 'Box-WOD, Cardio, Competition-Class, Early-Bird, Hyrox, MUM-Class, Mittags WOD, Strength Tuesday', 'CHF 1''790.00', 'einmalig', 10),
  ('Jahresabo Kids', '12 Monate gültig', 'Unbegrenzte Check-ins', 'KIDS-Class', 'CHF 490.00', 'einmalig', 11),
  ('Jahresabo Opengym', '12 Monate gültig', 'Unbegrenzte Check-ins', 'Open Gym', 'CHF 1''390.00', 'einmalig', 12),
  ('Jahresabo Silber', '12 Monate gültig', '2 Check-ins pro Woche', 'Box-WOD, Cardio, Competition-Class, Early-Bird, Hyrox, MUM-Class, Mittags WOD, Strength Tuesday', 'CHF 1''490.00', 'einmalig', 13),
  ('Jahresabo Student', '12 Monate gültig', 'Unbegrenzte Check-ins', 'Box-WOD, Cardio, Competition-Class, Early-Bird, Hyrox, MUM-Class, Mittags WOD, Strength Tuesday', 'CHF 1''390.00', 'einmalig', 14),
  ('Monatsabo Gold', '1 Monat gültig', 'Unbegrenzte Check-ins', 'Box-WOD, Cardio, Competition-Class, Early-Bird, Hyrox, MUM-Class, Mittags WOD, Strength Tuesday', 'CHF 180.00', 'pro Monat', 15),
  ('Monatsabo Opengym', '1 Monat gültig', 'Unbegrenzte Check-ins', 'Open Gym', 'CHF 110.00', 'pro Monat', 16),
  ('Monatsabo Silber', '1 Monat gültig', '2 Check-ins pro Woche', 'Box-WOD, Cardio, Competition-Class, Early-Bird, Hyrox, MUM-Class, Mittags WOD, Strength Tuesday', 'CHF 150.00', 'pro Monat', 17);
