-- Abo-Zuweisungen: welches Mitglied hat welches Abo (036 ist nur der
-- Katalog der Angebote). Admins pflegen die Zuweisungen in der
-- Nutzerverwaltung, Mitglieder sehen ihr eigenes Abo im Profil-Hub.
-- Reine Anzeige - es hängt (noch) keine Buchungslogik daran, z.B. werden
-- Check-in-Limits nicht durchgesetzt.

CREATE TABLE user_memberships (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  membership_id BIGINT NOT NULL REFERENCES memberships(id),
  starts_on DATE NOT NULL DEFAULT CURRENT_DATE,
  -- NULL = unbefristet; abgelaufene Zuweisungen bleiben als Historie stehen.
  ends_on DATE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX user_memberships_user_id_idx ON user_memberships (user_id);

ALTER TABLE user_memberships ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own membership assignments"
ON user_memberships FOR SELECT
USING (user_id = auth.uid() OR is_admin());

CREATE POLICY "Admins can insert membership assignments"
ON user_memberships FOR INSERT
WITH CHECK (is_admin());

CREATE POLICY "Admins can update membership assignments"
ON user_memberships FOR UPDATE
USING (is_admin());

CREATE POLICY "Admins can delete membership assignments"
ON user_memberships FOR DELETE
USING (is_admin());
